theme: jekyll-theme-architect
title: ""
description: ""
theme: jekyll-theme-architect
title: "Meu Portfólio"
description: "Bem-vindo ao meu portfólio de Inteligência Artificial e Automação."
show_downloads: false

# Personalização de cores
github:
  is_project_page: false

# Cores personalizadas
style: |
  body {
    background-color: #f8f9fa;
    color: #333;
  }
  h1, h2, h3 {
    color: #0056b3;
  }
  a {
    color: #007bff;
    text-decoration: none;
  }
  a:hover {
    text-decoration: underline;
  }
